import { TechniqueType } from "../models/models";

export const technique: TechniqueType[] = [
  {
    img: "src/img/terex-tlb.jpg",
    title: "Экскаватор-погрузчик Terex TLB 825",
    description: {
      bucketVolume: 1,
      maxDepth: 4.741,
      weight: 8.03,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 3000,
  },
  {
    img: "src/img/Doosan-S180W.jpg",
    title: "Экскаватор-колесный Doosan Solar 180W-V",
    description: {
      bucketVolume: 0.81,
      maxDepth: 6.006,
      weight: 17.7,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 4000,
  },
  {
    img: "src/img/sunward-SWE-205.jpg",
    title: "Гусиничный экскаватор Sunward SWE205",
    description: {
      bucketVolume: 1,
      maxDepth: 6.75,
      weight: 22.1,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 4000,
  },
  {
    img: "src/img/sunward-SWE-210.jpg",
    title: "Гусиничный экскаватор Sunward SWE210",
    description: {
      bucketVolume: 1,
      maxDepth: 6.75,
      weight: 21.3,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 4000,
  },
  {
    img: "src/img/ACE-TLB95.jpg",
    title: "Экскаватор-погрузчик ACE TLB95",
    description: {
      bucketVolume: 0.24,
      maxDepth: 4.25,
      weight: 8.1,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 3000,
  },
  {
    img: "src/img/sunward-SWE-60E.jpg",
    title: "Гусиничный экскаватор Sunward SWE60E",
    description: {
      bucketVolume: 0.22,
      maxDepth: 3.73,
      weight: 6.0,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 2500,
  },
  {
    img: "src/img/LGCE-E6210F.jpg",
    title: "Гусиничный экскаватор LGCE-E6210F",
    description: {
      bucketVolume: 1,
      maxDepth: 6.73,
      weight: 21.25,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 4000,
  },
  {
    img: "src/img/sunward-SWE150W.jpg",
    title: "Колесный экскаватор Sunward-SWE150W",
    description: {
      bucketVolume: 0.6,
      maxDepth: 4.815,
      weight: 13.85,
      loadCapacityAuto: 0,
      loadCapacityArrow: 0,
      boomReach: 0,
      sideLength: 0,
    },
    price: 4000,
  },
  {
    img: "src/img/FAW.png",
    title: "Манипулятор FAW",
    description: {
      bucketVolume: 0,
      maxDepth: 0,
      weight: 0,
      loadCapacityAuto: 30,
      loadCapacityArrow: 8,
      boomReach: 19,
      sideLength: 6.2,
    },
    price: 4750,
  },
];
